# Naming generated clusters using gemini

In [2]:
import pandas as pd
import time
import os
import json

In [11]:
num_clusters = 120
reduction_method = "umap"
df = pd.read_csv(f'data/processed/plotly/starmap_data_big_{reduction_method}_{num_clusters}.csv')
df.head()

,id,title,description,thumbnail,youtube_url,cluster_id,x,y,z
0,fandom_433761,ねくろちゃん -Yamaguro Nekuro- /あおぎり高校,Nekuro Yamaguro is a Japanese VTuber affiliate...,https://static.wikia.nocookie.net/youtube/imag...,https://www.youtube.com/channel/UCs-lYkwb-NYKE...,0,-0.727197,10.546905,5.342109
1,fandom_400167,Mary Channel / 西園寺メアリ【ハニスト】,Mary Saionji (西園寺メアリ) is a Japanese VTuber and...,https://static.wikia.nocookie.net/youtube/imag...,https://www.youtube.com/channel/UCwePpiw1ocZRS...,0,-0.955110,10.465550,5.570381
2,fandom_429720,Shirose aoiCh.白瀬 あおい / プロプロ,Aoi Shirose (Japanese: 白瀬あおい; born: December 3...,https://static.wikia.nocookie.net/youtube/imag...,https://www.youtube.com/channel/UC4SUl-nTftCcl...,0,-1.058549,10.540133,5.636990
3,fandom_480785,Ori Ch.,Orihime[citation needed] (birthday: September ...,https://static.wikia.nocookie.net/youtube/imag...,https://www.youtube.com/channel/UC-RE-kqCuteJr...,0,-1.195375,10.600286,5.538631
4,fandom_419300,たまえりライブチャンネル【PinkPunkPro所属】,Erina Tamaki is a Japanese VTuber who is part ...,https://static.wikia.nocookie.net/youtube/imag...,https://www.youtube.com/channel/UCTew_otbB25Ui...,0,-0.758095,10.401288,5.492359

## Get new df, with descriptions cut to 3000 characters and cluster groups only

In [12]:
df_gemini = df[["title", "description", "cluster_id"]]
df_gemini.head()

,title,description,cluster_id
0,ねくろちゃん -Yamaguro Nekuro- /あおぎり高校,Nekuro Yamaguro is a Japanese VTuber affiliate...,0
1,Mary Channel / 西園寺メアリ【ハニスト】,Mary Saionji (西園寺メアリ) is a Japanese VTuber and...,0
2,Shirose aoiCh.白瀬 あおい / プロプロ,Aoi Shirose (Japanese: 白瀬あおい; born: December 3...,0
3,Ori Ch.,Orihime[citation needed] (birthday: September ...,0
4,たまえりライブチャンネル【PinkPunkPro所属】,Erina Tamaki is a Japanese VTuber who is part ...,0

## Reduce description down to 3000

Ran out of quota. Doing a sloppy way instead

In [ ]:
# df_gemini['description'] = df_gemini['description'].str[:3000]

/var/folders/w7/kp2_hvs50r57qw4_9vn5k0tr0000gn/T/ipykernel_64478/214877023.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_gemini['description'] = df_gemini['description'].str[:3000]

Save to a file, then give it to gemini pro

In [13]:
df_gemini.to_csv(f'data/processed/plotly/starmap_data_big_{reduction_method}_trimmed_{num_clusters}.csv', index=False)

In [21]:
labels = {
    0: "Japanese VTubers & Chatting",
    1: "Sonic the Hedgehog & Fan Games",
    2: "True Crime & Social Commentary",
    3: "Animation & GoAnimate/Vyond",
    4: "Twitch Streamers & Highlights",
    5: "Fighting Games & RPGs",
    6: "Minecraft Commentary & SMPs",
    7: "Influencer Boxing & Commentary",
    8: "Sketch Comedy & Parodies",
    9: "Classic Pop & Soul Music",
    10: "Comics, Cartoons & Lore",
    11: "Anime Covers & Utaite",
    12: "Drama Commentary & Tea",
    13: "Geometry Dash Levels & Demons",
    14: "Object Shows & Animation",
    15: "Roblox Development & Gameplay",
    16: "Retail & Corporate Brands",
    17: "Educational & Video Essays",
    18: "Social Commentary & Lifestyle",
    19: "Minecraft PvP & Minigames",
    20: "Cartoon Reviews & Analysis",
    21: "Aviation & Travel Industry",
    22: "Mobile Strategy Games (Supercell)",
    23: "Roblox Gameplay & Humor",
    24: "Cat Videos & Memes",
    25: "Middle Eastern Vlogs & Lifestyle",
    26: "2D Animation & Art",
    27: "Horror, ARGs & Internet Mysteries",
    28: "GTA V & Rockstar Games",
    29: "British Commentary & Variety",
    30: "Friday Night Funkin' (FNF)",
    31: "Instrumental Covers & Musicians",
    32: "Dog Videos & Animal Facts",
    33: "Internet Culture & Rants",
    34: "Rock Bands & Classic Rock",
    35: "Team Fortress 2 (TF2)",
    36: "Variety Vlogs & Challenges",
    37: "Ice Hockey (NHL)",
    38: "Geek Culture & Web Series",
    39: "Pop Stars & Chart Music",
    40: "Movie Reviews & Theme Parks",
    41: "Minecraft Survival & SMPs",
    42: "Hololive & VTubers",
    43: "Roblox Simulators & Tycoons",
    44: "Urban Planning & Tech History",
    45: "Voice Actors & Variety Content",
    46: "Mapping & History Visualization",
    47: "Atheism, Skepticism & Philosophy",
    48: "Electronic Music & Remixes",
    49: "Cartoon Memes & Shitposting",
    50: "Strategy & City Building Games",
    51: "J-Pop & Anime Music",
    52: "Minecraft Variety (International)",
    53: "TV Shows & Talk Shows",
    54: "Indie Music & EDM",
    55: "Gacha Life & Stories",
    56: "Spongebob Parodies & YTPs",
    57: "Gaming News & Esports",
    58: "Mobile Gaming (Clash/Brawl)",
    59: "Family Vlogs & Kids",
    60: "Slavic Life & Gaming",
    61: "Storytime & Variety Gaming",
    62: "Memes & Internet Humor",
    63: "Indie Animation & Shorts",
    64: "FNAF Animation & Fangames",
    65: "Tech Giants & Software",
    66: "Food Reviews & Culinary",
    67: "Fortnite & Competitive Gaming",
    68: "Eurovision & International Pop",
    69: "Travel & Expat Vlogs",
    70: "Countryballs & Mapping",
    71: "Diecast Cars & Restoration",
    72: "Consumer Brands & Products",
    73: "Storytime Animation",
    74: "Cooking & Street Food",
    75: "Nursery Rhymes & Kids TV",
    76: "Commentary & Podcasts",
    77: "Lifestyle & Social Commentary",
    78: "TV Networks & Media",
    79: "Hip-Hop & Rap Artists",
    80: "Mario & Nintendo Gaming",
    81: "Game Studios & Toys",
    82: "Political Commentary & Culture War",
    83: "Science & History Education",
    84: "Anime Aesthetics & Music",
    85: "Asian Media & Broadcasting",
    86: "Government & Public Services",
    87: "Gaming Commentary & Video Essays",
    88: "Digital Art & Speedpaints",
    89: "Thomas the Tank Engine Fans",
    90: "British Comedy & Commentary",
    91: "Football (Soccer) & Federations",
    92: "DJs & Electronic Music",
    93: "Food & Beverage Brands",
    94: "Global Sports & MMA",
    95: "Rap Battles & Parodies",
    96: "Roblox Aesthetic & Roleplay",
    97: "China Vlogs & Commentary",
    98: "LEGO & Cubing",
    99: "Tech Reviews & DIY",
    100: "Stick Figure & Flash Animation",
    101: "Gacha Memes & Trends",
    102: "Indie VTubers",
    103: "Latin American Vlogs & Gaming",
    104: "Nintendo Variety",
    105: "ASMR",
    106: "Fast Food Chains",
    107: "Mainstream Hip-Hop",
    108: "Tourism & Travel Guides",
    109: "International Media & Vlogs",
    110: "Beauty & Lifestyle Influencers",
    111: "Anime Reviews & Analysis",
    112: "K-Pop Groups",
    113: "US Politicians & Politics",
    114: "Nijisanji & JP VTubers",
    115: "Metal & Hard Rock",
    116: "Indian Tech & Vlogs",
    117: "African Vlogs & Lifestyle",
    118: "Southeast Asian Content",
    119: "NBA Teams"
}

Open the csv file, replace the cluster ID with a string name, then save as a new file

In [22]:
df_combined = pd.read_csv(f'data/processed/plotly/starmap_data_big_{reduction_method}_{num_clusters}.csv')

In [23]:
df_combined['cluster_name'] = df_combined['cluster_id'].map(labels)
df_combined['cluster_name'].unique()

array(['Japanese VTubers & Chatting', 'Sonic the Hedgehog & Fan Games',
       'True Crime & Social Commentary', 'Animation & GoAnimate/Vyond',
       'Twitch Streamers & Highlights', 'Fighting Games & RPGs',
       'Minecraft Commentary & SMPs', 'Influencer Boxing & Commentary',
       'Sketch Comedy & Parodies', 'Classic Pop & Soul Music',
       'Comics, Cartoons & Lore', 'Anime Covers & Utaite',
       'Drama Commentary & Tea', 'Geometry Dash Levels & Demons',
       'Object Shows & Animation', 'Roblox Development & Gameplay',
       'Retail & Corporate Brands', 'Educational & Video Essays',
       'Social Commentary & Lifestyle', 'Minecraft PvP & Minigames',
       'Cartoon Reviews & Analysis', 'Aviation & Travel Industry',
       'Mobile Strategy Games (Supercell)', 'Roblox Gameplay & Humor',
       'Cat Videos & Memes', 'Middle Eastern Vlogs & Lifestyle',
       '2D Animation & Art', 'Horror, ARGs & Internet Mysteries',
       'GTA V & Rockstar Games', 'British Commentary & Variety',
       "Friday Night Funkin' (FNF)", 'Instrumental Covers & Musicians',
       'Dog Videos & Animal Facts', 'Internet Culture & Rants',
       'Rock Bands & Classic Rock', 'Team Fortress 2 (TF2)',
       'Variety Vlogs & Challenges', 'Ice Hockey (NHL)',
       'Geek Culture & Web Series', 'Pop Stars & Chart Music',
       'Movie Reviews & Theme Parks', 'Minecraft Survival & SMPs',
       'Hololive & VTubers', 'Roblox Simulators & Tycoons',
       'Urban Planning & Tech History', 'Voice Actors & Variety Content',
       'Mapping & History Visualization',
       'Atheism, Skepticism & Philosophy', 'Electronic Music & Remixes',
       'Cartoon Memes & Shitposting', 'Strategy & City Building Games',
       'J-Pop & Anime Music', 'Minecraft Variety (International)',
       'TV Shows & Talk Shows', 'Indie Music & EDM',
       'Gacha Life & Stories', 'Spongebob Parodies & YTPs',
       'Gaming News & Esports', 'Mobile Gaming (Clash/Brawl)',
       'Family Vlogs & Kids', 'Slavic Life & Gaming',
       'Storytime & Variety Gaming', 'Memes & Internet Humor',
       'Indie Animation & Shorts', 'FNAF Animation & Fangames',
       'Tech Giants & Software', 'Food Reviews & Culinary',
       'Fortnite & Competitive Gaming', 'Eurovision & International Pop',
       'Travel & Expat Vlogs', 'Countryballs & Mapping',
       'Diecast Cars & Restoration', 'Consumer Brands & Products',
       'Storytime Animation', 'Cooking & Street Food',
       'Nursery Rhymes & Kids TV', 'Commentary & Podcasts',
       'Lifestyle & Social Commentary', 'TV Networks & Media',
       'Hip-Hop & Rap Artists', 'Mario & Nintendo Gaming',
       'Game Studios & Toys', 'Political Commentary & Culture War',
       'Science & History Education', 'Anime Aesthetics & Music',
       'Asian Media & Broadcasting', 'Government & Public Services',
       'Gaming Commentary & Video Essays', 'Digital Art & Speedpaints',
       'Thomas the Tank Engine Fans', 'British Comedy & Commentary',
       'Football (Soccer) & Federations', 'DJs & Electronic Music',
       'Food & Beverage Brands', 'Global Sports & MMA',
       'Rap Battles & Parodies', 'Roblox Aesthetic & Roleplay',
       'China Vlogs & Commentary', 'LEGO & Cubing', 'Tech Reviews & DIY',
       'Stick Figure & Flash Animation', 'Gacha Memes & Trends',
       'Indie VTubers', 'Latin American Vlogs & Gaming',
       'Nintendo Variety', 'ASMR', 'Fast Food Chains',
       'Mainstream Hip-Hop', 'Tourism & Travel Guides',
       'International Media & Vlogs', 'Beauty & Lifestyle Influencers',
       'Anime Reviews & Analysis', 'K-Pop Groups',
       'US Politicians & Politics', 'Nijisanji & JP VTubers',
       'Metal & Hard Rock', 'Indian Tech & Vlogs',
       'African Vlogs & Lifestyle', 'Southeast Asian Content',
       'NBA Teams'], dtype=object)

In [24]:
df_combined['cluster_name'] = df_combined['cluster_id'].map(labels)
df_combined.to_csv(f'data/processed/plotly/starmap_data_big_{reduction_method}_trimmed_{num_clusters}_labeled.csv', index=False)

Save to a new csv

In [10]:
len(df_combined['cluster_name'].unique())

120